---
- hosts: leafs_DC1
  gather_facts: no
  tasks:
  - name: Register variables
    include_vars:
      file: "{{lookup('env','PWD')}}/vars/vars1.yml"
      name: variables1
    tags:
    - build
  - name: Create configurations
    template:
      src: "{{lookup('env','PWD')}}/templates/template3.j2"
      dest: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_learn3.cfg"
    tags:
    - build
